services:
  - type: web
    name: gathering-assistant
    env: node
    buildCommand: |
      npm install
      pip install -r requirements.txt
    startCommand: npm start
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: PERPLEXITY_API_KEY
        sync: false 